import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  caseStudiesSidebar: [{type: 'autogenerated', dirName: 'case-studies'}],
};

export default sidebars;
